<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<RootNamespace>GreenSwamp.Alpaca.Themes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Avalonia" Version="12.1.2" />
	<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>
</Project>
